name: powersync_sqlite_core_tests
publish_to: "none"
version: 0.0.1
description: Tests for powersync-sqlite-core
environment:
  sdk: ^3.4.0
dependencies:
  sqlite3: ^2.4.5
  meta: ^1.0.0
  uuid: ^4.2.0
dev_dependencies:
  dcli: ^4.0.0
  lints: ^3.0.0
  test: ^1.25.0
  test_api: ^0.7.0
  path_provider: ^2.0.13
  path: ^1.8.3
