name: "Upload binary file"
description: "Upload binary file to GitHub releases"
inputs:
  repo-token:
    required: true
    description: "The secret created for the workflow run"
  file-name:
    required: true
    description: "The file name to be uploaded"
  tag:
    required: false
    description: "The short ref name of the branch or tag that triggered the workflow run."
    default: ${{ github.ref_name }}
runs:
  using: "composite"
  steps:
    - name: Upload binary
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh release upload "${{ inputs.tag }}" "${{ inputs.file-name }}"
