on:
  push:
  pull_request:
name: "android"
jobs:
  build:
    name: Building Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Setup
        run: |
          rustup toolchain install nightly-2024-05-18-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2024-05-18-unknown-linux-gnu
          rustup target add \
            aarch64-linux-android \
            armv7-linux-androideabi \
            x86_64-linux-android \
            i686-linux-android
          cargo install cargo-ndk

      - name: Build for Android
        run: |
          cd android
          ./gradlew build
          ls -lh build/outputs/aar
