on:
  push:
  pull_request:
name: "ios"
jobs:
  build:
    name: Building Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        run: |
          rustup toolchain install nightly-2023-08-28-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-08-28-x86_64-unknown-linux-gnu
          rustup target add \
            aarch64-apple-ios \
            aarch64-apple-ios-sim \
            x86_64-apple-ios

      - name: Build iOS Pod
        run: |
          ./build-pod.sh
