on:
  push:
  workflow_dispatch:
name: "macos"
jobs:
  build_macOS_aarch64:
    name: Building macOS aarch64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build binary
        run: bash tool/build_macos.sh aarch64

      - name: Upload binary
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/upload
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          file-name: libpowersync_aarch64.dylib
          tag: ${{ github.ref_name }}

  build_macOS_x64:
    name: Building macOS x64
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build binary
        run: bash tool/build_macos.sh x64

      - name: Upload binary
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/upload
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          file-name: libpowersync_x64.dylib
          tag: ${{ github.ref_name }}
