on:
  push:
name: "tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dart-lang/setup-dart@v1

      - name: Ubuntu setup
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt install libreadline-dev

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-05-18
          components: rust-src

      - name: Build
        run: |
          # Need a debug build for the dart tests
          cargo build -p powersync_loadable -Z build-std=panic_abort,core,alloc --release --target x86_64-unknown-linux-gnu

          cargo build -p powersync_loadable --release
          cargo build -p powersync_core --release --features static
          cargo build -p powersync_sqlite --release
          cargo build -p sqlite3 --release

      - name: Test powersync
        run: |
          cargo test -p powersync_core --features loadable_extension

      - name: Check shell
        run: |
          ./target/release/powersync_sqlite ":memory:" "select powersync_rs_version()"

      - name: Check loadable extension
        run: |
          ./target/release/sqlite3 ":memory:" ".load ./target/release/libpowersync" "select powersync_rs_version()"

      - name: Run dart-based tests
        # Extension loading fails on macos currently
        if: matrix.os == 'ubuntu-24.04'
        run: |
          cd dart
          dart pub get
          dart test
          dart analyze
