on:
  push:
  pull_request:
name: "rs-valgrind"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install valgrind
        run: sudo apt install -y valgrind

      - name: Install Cargo Valgrind
        run: |
          cargo install cargo-valgrind

      - name: Test Core
        run: |
          cargo valgrind test -p powersync_core --features loadable_extension
