on:
  push:
name: "windows"
jobs:
  build_windows:
    name: Building Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-05-18
          components: rust-src

      - name: Build binary
        run: ./tool/build_windows.sh x64
