on:
  push:
name: "windows"
jobs:
  build_windows:
    name: Building Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        run: |
          rustup toolchain install nightly-2024-05-18-x86_64-pc-windows-msvc
          rustup component add rust-src --toolchain nightly-2024-05-18-x86_64-pc-windows-msvc

      - name: Build binary
        run: ./tool/build_windows.sh x64

      - name: Upload binary
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/upload
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          file-name: powersync_x64.dll
          tag: ${{ github.ref_name }}
